const aliases = {
  name:['name','nombre','client','cliente','buyer','comprador'],email:['email','correo','e-mail'],phone:['phone','telefono','teléfono','mobile','movil','móvil'],nationality:['nationality','nacionalidad'],
  minBudget:['minbudget','min_budget','presupuestomin','presupuesto_min','budgetmin'],maxBudget:['maxbudget','max_budget','presupuestomax','presupuesto_max','budgetmax','budget'],currency:['currency','moneda'],
  desiredLocations:['desiredlocations','desired_locations','zonas','locations','ubicaciones','location'],propertyTypes:['propertytypes','property_types','tipo','tipos','propertytype'],minBedrooms:['minbedrooms','min_bedrooms','dormitorios','habitaciones','bedrooms'],desiredFeatures:['desiredfeatures','desired_features','extras','features','caracteristicas','características'],purchaseTimeline:['purchasetimeline','purchase_timeline','plazo','timeline'],financingType:['financingtype','financing_type','financiacion','financiación'],status:['status','estado'],notes:['notes','notas','observaciones']
};
const canon=(value)=>String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_]/g,'');
const splitCsvLine=(line)=>{const cells=[];let cell='';let quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(quoted&&line[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(c===','&&!quoted){cells.push(cell);cell='';}else cell+=c;}cells.push(cell);return cells;};
const list=(value)=>String(value??'').split(/[;|]/).map((item)=>item.trim()).filter(Boolean);
const number=(value)=>{const normalized=String(value??'').replace(/[^0-9.,]/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.');const n=Number(normalized);return Number.isFinite(n)?n:undefined;};
function valueFor(row,key){const wanted=aliases[key].map(canon);const actual=Object.keys(row).find((header)=>wanted.includes(canon(header)));return actual?row[actual]:undefined;}
export function parseBuyerCsv(text){const lines=text.replace(/\r/g,'').split('\n').filter((line)=>line.trim());if(lines.length<2)return{buyers:[],errors:['El CSV no contiene filas de datos']};const headers=splitCsvLine(lines[0]).map((h)=>h.trim());const buyers=[];const errors=[];for(let i=1;i<lines.length;i++){const cells=splitCsvLine(lines[i]);const row=Object.fromEntries(headers.map((header,index)=>[header,cells[index]??'']));const name=String(valueFor(row,'name')??'').trim();if(!name){errors.push(`Fila ${i+1}: falta el nombre del comprador`);continue;}const rawStatus=canon(valueFor(row,'status')||'lead');const status=['lead','qualified','active','paused','won','lost'].includes(rawStatus)?rawStatus:'lead';const rawFinancing=canon(valueFor(row,'financingType')||'unknown');const financingType=['cash','finance','unknown'].includes(rawFinancing)?rawFinancing:'unknown';buyers.push({id:`import-${Date.now()}-${i}`,name,email:String(valueFor(row,'email')??'').trim()||undefined,phone:String(valueFor(row,'phone')??'').trim()||undefined,nationality:String(valueFor(row,'nationality')??'').trim()||undefined,minBudget:number(valueFor(row,'minBudget')),maxBudget:number(valueFor(row,'maxBudget')),currency:String(valueFor(row,'currency')||'EUR').trim().toUpperCase(),desiredLocations:list(valueFor(row,'desiredLocations')),propertyTypes:list(valueFor(row,'propertyTypes')),minBedrooms:number(valueFor(row,'minBedrooms')),desiredFeatures:list(valueFor(row,'desiredFeatures')),purchaseTimeline:String(valueFor(row,'purchaseTimeline')??'').trim()||undefined,financingType,status,notes:String(valueFor(row,'notes')??'').trim()||undefined});}return{buyers,errors};}
