export const demoProperties = [
  { id:'p1',title:'Villa Aurelia',status:'public',price:6900000,currency:'EUR',propertyType:'Villa',city:'Marbella',region:'Andalusia',neighborhood:'Sierra Blanca',bedrooms:6,bathrooms:7,builtM2:880,plotM2:2400,features:['Sea view','Pool','Home cinema','Gym','Garage','Gated community'],heroImage:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1600&q=85',createdAt:'2026-09-11T08:00:00Z' },
  { id:'p2',title:'Casa Perla',status:'public',price:5450000,currency:'EUR',propertyType:'Villa',city:'Marbella',region:'Andalusia',neighborhood:'Golden Mile',bedrooms:5,bathrooms:6,builtM2:650,plotM2:1500,features:['Pool','Garage','Guest house','Solar'],heroImage:'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1600&q=85',createdAt:'2026-09-10T08:00:00Z' },
  { id:'p3',title:'Villa Monteverde',status:'off_market',price:14500000,currency:'EUR',propertyType:'Estate',city:'Benahavís',region:'Andalusia',neighborhood:'La Zagaleta',bedrooms:8,bathrooms:9,builtM2:1750,plotM2:7800,features:['Sea view','Pool','Spa','Gym','Home cinema','Staff quarters','Golf access','Gated community'],heroImage:'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&w=1600&q=85',createdAt:'2026-09-09T08:00:00Z' },
  { id:'p4',title:'Cortijo Alma',status:'private',price:4750000,currency:'EUR',propertyType:'Country house',city:'Benahavís',region:'Andalusia',neighborhood:'El Madroñal',bedrooms:5,bathrooms:4,builtM2:540,plotM2:4200,features:['Pool','Guest house','Wine cellar','Gated community','Solar'],heroImage:'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1600&q=85',createdAt:'2026-09-08T08:00:00Z' },
  { id:'p5',title:'Casa Levante',status:'public',price:3900000,currency:'EUR',propertyType:'Villa',city:'Sotogrande',region:'Cádiz',neighborhood:'Sotogrande Costa',bedrooms:4,bathrooms:4,builtM2:410,plotM2:1800,features:['Beachfront','Sea view','Pool','Garage'],heroImage:'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=1600&q=85',createdAt:'2026-09-07T08:00:00Z' },
  { id:'p6',title:'La Reserva Residence',status:'public',price:5250000,currency:'EUR',propertyType:'Villa',city:'Sotogrande',region:'Cádiz',neighborhood:'La Reserva',bedrooms:5,bathrooms:6,builtM2:720,plotM2:2900,features:['Golf access','Pool','Gym','Gated community','Solar','Lift'],heroImage:'https://images.unsplash.com/photo-1602343168117-bb8ffe3e2e9f?auto=format&fit=crop&w=1600&q=85',createdAt:'2026-09-06T08:00:00Z' },
  { id:'p7',title:'Penthouse Marés',status:'reserved',price:2850000,currency:'EUR',propertyType:'Penthouse',city:'Marbella',region:'Andalusia',neighborhood:'Puerto Banús',bedrooms:3,bathrooms:3,builtM2:290,plotM2:0,features:['Sea view','Pool','Lift','Garage','Gym'],heroImage:'https://images.unsplash.com/photo-1615874959474-d609969a20ed?auto=format&fit=crop&w=1600&q=85',createdAt:'2026-09-05T08:00:00Z' },
  { id:'p8',title:'Finca Los Olivos',status:'draft',price:3200000,currency:'EUR',propertyType:'Finca',city:'Benahavís',region:'Andalusia',neighborhood:'Inland Benahavís',bedrooms:7,bathrooms:5,builtM2:860,plotM2:110000,features:['Guest house','Pool','Solar','Wine cellar'],heroImage:'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=1600&q=85',createdAt:'2026-09-04T08:00:00Z' }
];

export const demoBuyers = [
  { id:'b1',name:'H. Lindqvist',email:'h.lindqvist@example.com',nationality:'Swedish',minBudget:6000000,maxBudget:10000000,currency:'EUR',desiredLocations:['Marbella','Sierra Blanca'],propertyTypes:['Villa','Estate'],minBedrooms:5,desiredFeatures:['Sea view','Pool','Home cinema'],purchaseTimeline:'3-6 months',financingType:'cash',status:'active',notes:'Prioritises privacy and sea views.' },
  { id:'b2',name:'The Ashworth Family',email:'ashworth@example.com',nationality:'British',minBudget:3000000,maxBudget:5500000,currency:'EUR',desiredLocations:['Sotogrande'],propertyTypes:['Villa'],minBedrooms:4,desiredFeatures:['Golf access','Pool'],purchaseTimeline:'6-12 months',financingType:'finance',status:'qualified' },
  { id:'b3',name:'M. Reinhardt',email:'m.reinhardt@example.com',nationality:'German',minBudget:10000000,maxBudget:18000000,currency:'EUR',desiredLocations:['Benahavís','La Zagaleta'],propertyTypes:['Estate','Villa'],minBedrooms:7,desiredFeatures:['Spa','Staff quarters','Gated community','Home cinema'],purchaseTimeline:'Immediate',financingType:'cash',status:'active',notes:'Off-market only. Discretion required.' },
  { id:'b4',name:'Sofia Berg',email:'s.berg@example.com',nationality:'Norwegian',minBudget:3500000,maxBudget:5000000,currency:'EUR',desiredLocations:['Benahavís'],propertyTypes:['Country house','Finca'],minBedrooms:4,desiredFeatures:['Pool','Guest house'],purchaseTimeline:'6-12 months',financingType:'cash',status:'qualified' },
  { id:'b5',name:'J. Callender',email:'j.callender@example.com',nationality:'American',minBudget:2500000,maxBudget:3500000,currency:'EUR',desiredLocations:['Marbella','Puerto Banús'],propertyTypes:['Penthouse','Apartment'],minBedrooms:3,desiredFeatures:['Sea view','Lift','Garage'],purchaseTimeline:'3-6 months',financingType:'cash',status:'active' },
  { id:'b6',name:'Familie Vermeer',email:'vermeer@example.com',nationality:'Dutch',minBudget:3500000,maxBudget:4200000,currency:'EUR',desiredLocations:['Sotogrande','Cádiz'],propertyTypes:['Villa'],minBedrooms:4,desiredFeatures:['Beachfront','Sea view'],purchaseTimeline:'12+ months',financingType:'finance',status:'lead' },
  { id:'b7',name:'A. Nasser',email:'a.nasser@example.com',nationality:'Emirati',minBudget:8000000,maxBudget:15000000,currency:'EUR',desiredLocations:['Marbella','Benahavís'],propertyTypes:['Villa','Estate'],minBedrooms:6,desiredFeatures:['Staff quarters','Spa','Gated community'],purchaseTimeline:'Immediate',financingType:'cash',status:'qualified' },
  { id:'b8',name:'L. Moreau',email:'l.moreau@example.com',nationality:'French',minBudget:5000000,maxBudget:7000000,currency:'EUR',desiredLocations:['Marbella','Golden Mile'],propertyTypes:['Villa'],minBedrooms:5,desiredFeatures:['Pool','Guest house','Garage'],purchaseTimeline:'3-6 months',financingType:'unknown',status:'active' },
  { id:'b9',name:'K. Novak',email:'k.novak@example.com',nationality:'Czech',minBudget:4500000,maxBudget:6000000,currency:'EUR',desiredLocations:['Sotogrande','La Reserva'],propertyTypes:['Villa'],minBedrooms:5,desiredFeatures:['Golf access','Gym','Solar'],purchaseTimeline:'6-12 months',financingType:'finance',status:'paused' },
  { id:'b10',name:'R. Salvatierra',email:'r.salvatierra@example.com',nationality:'Spanish',minBudget:2000000,maxBudget:3000000,currency:'EUR',desiredLocations:['Marbella'],propertyTypes:['Penthouse','Villa'],minBedrooms:3,desiredFeatures:['Sea view','Pool'],purchaseTimeline:'12+ months',financingType:'finance',status:'lead' }
];
